// Code generated by ent, DO NOT EDIT.

package serviceapi

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the serviceapi type in the database.
	Label = "service_api"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldDomains holds the string denoting the domains field in the database.
	FieldDomains = "domains"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldMethodName holds the string denoting the method_name field in the database.
	FieldMethodName = "method_name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldExported holds the string denoting the exported field in the database.
	FieldExported = "exported"
	// FieldPathPrefix holds the string denoting the path_prefix field in the database.
	FieldPathPrefix = "path_prefix"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// Table holds the table name of the serviceapi in the database.
	Table = "service_ap_is"
)

// Columns holds all SQL columns for serviceapi fields.
var Columns = []string{
	FieldID,
	FieldProtocol,
	FieldServiceName,
	FieldDomains,
	FieldMethod,
	FieldMethodName,
	FieldPath,
	FieldExported,
	FieldPathPrefix,
	FieldCreateAt,
	FieldUpdateAt,
	FieldDeleteAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() uint32
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() uint32
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() uint32
	// DefaultDeleteAt holds the default value on creation for the "delete_at" field.
	DefaultDeleteAt func() uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
