// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServiceApIsColumns holds the columns for the "service_ap_is" table.
	ServiceApIsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "protocol", Type: field.TypeString},
		{Name: "service_name", Type: field.TypeString},
		{Name: "domains", Type: field.TypeJSON},
		{Name: "method", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "exported", Type: field.TypeBool},
		{Name: "path_prefix", Type: field.TypeString},
		{Name: "method_name", Type: field.TypeString},
		{Name: "create_at", Type: field.TypeUint32},
		{Name: "update_at", Type: field.TypeUint32},
		{Name: "delete_at", Type: field.TypeUint32},
	}
	// ServiceApIsTable holds the schema information for the "service_ap_is" table.
	ServiceApIsTable = &schema.Table{
		Name:       "service_ap_is",
		Columns:    ServiceApIsColumns,
		PrimaryKey: []*schema.Column{ServiceApIsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "serviceapi_service_name_method_path",
				Unique:  true,
				Columns: []*schema.Column{ServiceApIsColumns[2], ServiceApIsColumns[4], ServiceApIsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServiceApIsTable,
	}
)

func init() {
}
