// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/api-manager/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/api-manager/pkg/db/ent/serviceapi"
	"github.com/google/uuid"
)

// ServiceAPIQuery is the builder for querying ServiceAPI entities.
type ServiceAPIQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ServiceAPI
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServiceAPIQuery builder.
func (saq *ServiceAPIQuery) Where(ps ...predicate.ServiceAPI) *ServiceAPIQuery {
	saq.predicates = append(saq.predicates, ps...)
	return saq
}

// Limit adds a limit step to the query.
func (saq *ServiceAPIQuery) Limit(limit int) *ServiceAPIQuery {
	saq.limit = &limit
	return saq
}

// Offset adds an offset step to the query.
func (saq *ServiceAPIQuery) Offset(offset int) *ServiceAPIQuery {
	saq.offset = &offset
	return saq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (saq *ServiceAPIQuery) Unique(unique bool) *ServiceAPIQuery {
	saq.unique = &unique
	return saq
}

// Order adds an order step to the query.
func (saq *ServiceAPIQuery) Order(o ...OrderFunc) *ServiceAPIQuery {
	saq.order = append(saq.order, o...)
	return saq
}

// First returns the first ServiceAPI entity from the query.
// Returns a *NotFoundError when no ServiceAPI was found.
func (saq *ServiceAPIQuery) First(ctx context.Context) (*ServiceAPI, error) {
	nodes, err := saq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{serviceapi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (saq *ServiceAPIQuery) FirstX(ctx context.Context) *ServiceAPI {
	node, err := saq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServiceAPI ID from the query.
// Returns a *NotFoundError when no ServiceAPI ID was found.
func (saq *ServiceAPIQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = saq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{serviceapi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (saq *ServiceAPIQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := saq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServiceAPI entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServiceAPI entity is found.
// Returns a *NotFoundError when no ServiceAPI entities are found.
func (saq *ServiceAPIQuery) Only(ctx context.Context) (*ServiceAPI, error) {
	nodes, err := saq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{serviceapi.Label}
	default:
		return nil, &NotSingularError{serviceapi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (saq *ServiceAPIQuery) OnlyX(ctx context.Context) *ServiceAPI {
	node, err := saq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServiceAPI ID in the query.
// Returns a *NotSingularError when more than one ServiceAPI ID is found.
// Returns a *NotFoundError when no entities are found.
func (saq *ServiceAPIQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = saq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{serviceapi.Label}
	default:
		err = &NotSingularError{serviceapi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (saq *ServiceAPIQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := saq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServiceAPIs.
func (saq *ServiceAPIQuery) All(ctx context.Context) ([]*ServiceAPI, error) {
	if err := saq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return saq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (saq *ServiceAPIQuery) AllX(ctx context.Context) []*ServiceAPI {
	nodes, err := saq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServiceAPI IDs.
func (saq *ServiceAPIQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := saq.Select(serviceapi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (saq *ServiceAPIQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := saq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (saq *ServiceAPIQuery) Count(ctx context.Context) (int, error) {
	if err := saq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return saq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (saq *ServiceAPIQuery) CountX(ctx context.Context) int {
	count, err := saq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (saq *ServiceAPIQuery) Exist(ctx context.Context) (bool, error) {
	if err := saq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return saq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (saq *ServiceAPIQuery) ExistX(ctx context.Context) bool {
	exist, err := saq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServiceAPIQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (saq *ServiceAPIQuery) Clone() *ServiceAPIQuery {
	if saq == nil {
		return nil
	}
	return &ServiceAPIQuery{
		config:     saq.config,
		limit:      saq.limit,
		offset:     saq.offset,
		order:      append([]OrderFunc{}, saq.order...),
		predicates: append([]predicate.ServiceAPI{}, saq.predicates...),
		// clone intermediate query.
		sql:    saq.sql.Clone(),
		path:   saq.path,
		unique: saq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Protocol string `json:"protocol,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServiceAPI.Query().
//		GroupBy(serviceapi.FieldProtocol).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (saq *ServiceAPIQuery) GroupBy(field string, fields ...string) *ServiceAPIGroupBy {
	grbuild := &ServiceAPIGroupBy{config: saq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := saq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return saq.sqlQuery(ctx), nil
	}
	grbuild.label = serviceapi.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Protocol string `json:"protocol,omitempty"`
//	}
//
//	client.ServiceAPI.Query().
//		Select(serviceapi.FieldProtocol).
//		Scan(ctx, &v)
//
func (saq *ServiceAPIQuery) Select(fields ...string) *ServiceAPISelect {
	saq.fields = append(saq.fields, fields...)
	selbuild := &ServiceAPISelect{ServiceAPIQuery: saq}
	selbuild.label = serviceapi.Label
	selbuild.flds, selbuild.scan = &saq.fields, selbuild.Scan
	return selbuild
}

func (saq *ServiceAPIQuery) prepareQuery(ctx context.Context) error {
	for _, f := range saq.fields {
		if !serviceapi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if saq.path != nil {
		prev, err := saq.path(ctx)
		if err != nil {
			return err
		}
		saq.sql = prev
	}
	return nil
}

func (saq *ServiceAPIQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServiceAPI, error) {
	var (
		nodes = []*ServiceAPI{}
		_spec = saq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ServiceAPI).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ServiceAPI{config: saq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, saq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (saq *ServiceAPIQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := saq.querySpec()
	_spec.Node.Columns = saq.fields
	if len(saq.fields) > 0 {
		_spec.Unique = saq.unique != nil && *saq.unique
	}
	return sqlgraph.CountNodes(ctx, saq.driver, _spec)
}

func (saq *ServiceAPIQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := saq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (saq *ServiceAPIQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   serviceapi.Table,
			Columns: serviceapi.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: serviceapi.FieldID,
			},
		},
		From:   saq.sql,
		Unique: true,
	}
	if unique := saq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := saq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, serviceapi.FieldID)
		for i := range fields {
			if fields[i] != serviceapi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := saq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := saq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := saq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := saq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (saq *ServiceAPIQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(saq.driver.Dialect())
	t1 := builder.Table(serviceapi.Table)
	columns := saq.fields
	if len(columns) == 0 {
		columns = serviceapi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if saq.sql != nil {
		selector = saq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if saq.unique != nil && *saq.unique {
		selector.Distinct()
	}
	for _, p := range saq.predicates {
		p(selector)
	}
	for _, p := range saq.order {
		p(selector)
	}
	if offset := saq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := saq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServiceAPIGroupBy is the group-by builder for ServiceAPI entities.
type ServiceAPIGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sagb *ServiceAPIGroupBy) Aggregate(fns ...AggregateFunc) *ServiceAPIGroupBy {
	sagb.fns = append(sagb.fns, fns...)
	return sagb
}

// Scan applies the group-by query and scans the result into the given value.
func (sagb *ServiceAPIGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := sagb.path(ctx)
	if err != nil {
		return err
	}
	sagb.sql = query
	return sagb.sqlScan(ctx, v)
}

func (sagb *ServiceAPIGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range sagb.fields {
		if !serviceapi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := sagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (sagb *ServiceAPIGroupBy) sqlQuery() *sql.Selector {
	selector := sagb.sql.Select()
	aggregation := make([]string, 0, len(sagb.fns))
	for _, fn := range sagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(sagb.fields)+len(sagb.fns))
		for _, f := range sagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(sagb.fields...)...)
}

// ServiceAPISelect is the builder for selecting fields of ServiceAPI entities.
type ServiceAPISelect struct {
	*ServiceAPIQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sas *ServiceAPISelect) Scan(ctx context.Context, v interface{}) error {
	if err := sas.prepareQuery(ctx); err != nil {
		return err
	}
	sas.sql = sas.ServiceAPIQuery.sqlQuery(ctx)
	return sas.sqlScan(ctx, v)
}

func (sas *ServiceAPISelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := sas.sql.Query()
	if err := sas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
