// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ServiceAPI is the predicate function for serviceapi builders.
type ServiceAPI func(*sql.Selector)
